name: base
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - seaborn
  - streamlit
  - voila
