name: Build
on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  # Set to "" to publish container on tags only
  # Set to "<branch-name>" to also publish on every push to <branch-name>
  PUBLISH_BRANCH: "main"
  PLATFORMS: linux/amd64,linux/arm64

jobs:

  build:
    name: Build
    strategy:
      # Keep running so we can see if other tests pass
      fail-fast: false
      matrix:
        image:
          - jupyter-guacamole
          - ubuntu-mate-vnc
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=false
          images: ${{ env.REGISTRY }}/${{ matrix.image }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        if: >
          github.event_name == 'push' &&
          (github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH) ||
          startsWith(github.ref, 'refs/tags/'))
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to container registry
        uses: docker/build-push-action@v3
        with:
          # Needed so that .git directory is available to embed version info
          context: ${{ matrix.image }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: >
            ${{
              github.event_name == 'push' &&
              github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH) ||
              startsWith(github.ref, 'refs/tags/')
            }}